services:
  db:
    container_name: postgres
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  garnet:
    image: "ghcr.io/microsoft/garnet"
    ulimits:
      memlock: -1
    ports:
      - 6379:6379
    volumes:
      - garnetdata:/data
    restart: always

volumes:
  postgres-data:
  garnetdata:
